tasks:
  - init: pip install -U pytest

vscode:
  extensions:
    - ms-python.python
    - hbenl.vscode-test-explorer
    - hbenl.test-adapter-converter
    - littlefoxteam.vscode-python-test-adapter
